pipeline:
  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick
    secrets: [ clamav_repo_username, clamav_repo_token ]
    registry: quay.io
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - b${DRONE_BUILD_NUMBER}
    when:
      event: push
